version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout
      - run: docker build -t devops .
      - run: docker run devops yarn test


  deploy-job:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout
      - run:
          command:  sh deployments/qa.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
        filters:
          branches:
            only:
              - /feature_.*/
      - deploy-job:
        filters:
          branches:
            only:
              - /feature_.*/
